apiVersion: v1
kind: Service
metadata:
  name: usuario-microservice-service
  namespace: desenvolvimento
spec:
  selector:
    app: usuario-microservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP